@baseUrl = http://localhost:8000

# @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### get token
@token = {{login.response.body.token}}

### get features 
GET {{baseUrl}}/sachima/rule/商户评分卡/v0.1 HTTP/1.1
Authorization: Bearer {{token}} 

### get rules 
GET {{baseUrl}}/sachima/rules HTTP/1.1
Authorization: Bearer {{token}} 

### test casbin  
GET {{baseUrl}}/sachima/hello HTTP/1.1
Authorization: Bearer {{token}} 

### add user  
POST {{baseUrl}}/sachima/adduser HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

{
    "username": "admin",
    "password": "123456",
    "email":"admin@sachima.com",
    "firstname":"管理员",
    "lastname":"管理员"
}

# const mock_users = [
#     { id: 'wanghaoran', name: "王浩然" },
#     { id: 'duanyu', name: "段誉" },
#     { id: 'wangyuyan', name: "王语嫣" },
#     { id: 'xuzhu', name: "虚竹" },
#     { id: 'wanglihong', name: "王力宏" },
#     { id: 'admin', name: '管理员' }
# ]

### get roles
GET {{baseUrl}}/sachima/getroles HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

### get single rolexxxxxxxxxxxxxxxxxxxxxxxx
GET {{baseUrl}}/sachima/role/administrator HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

### get users
GET {{baseUrl}}/sachima/getusers HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

### get single userxxxxxxxxxxxxxxxxxxxxxxxx
GET {{baseUrl}}/sachima/user/wanghaoran HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

### get objects 
GET {{baseUrl}}/sachima/getobjects HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

### get single object
GET {{baseUrl}}/sachima/object/s0010 HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json


### get userrole
GET {{baseUrl}}/sachima/getuserrole HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json


### get role
GET {{baseUrl}}/sachima/getroleobject HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

