@baseUrl = http://localhost:8000

# @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### get token
@token = {{login.response.body.token}}

### get features 
GET {{baseUrl}}/sachima/features HTTP/1.1
Authorization: Bearer {{token}} 

### test casbin  
GET {{baseUrl}}/sachima/hello HTTP/1.1
Authorization: Bearer {{token}} 

### add user  
POST {{baseUrl}}/sachima/adduser HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

{
    "username": "jerry",
    "password": "88887777",
    "email":"john@sachima.com"
}

### get roles
POST {{baseUrl}}/sachima/getroles HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json