@baseUrl = http://localhost:8000

# @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### get token
@token = {{login.response.body.token}}

### get features 
GET http://localhost:8000/sachima/features HTTP/1.1
Authorization: Bearer {{token}} 

### test casbin  
GET http://localhost:8000/sachima/hello HTTP/1.1
Authorization: Bearer {{token}} 